ArcanasData = {
 'Chariot': [['Fool', 'Lovers'],
             ['Magician', 'Temperance'],
             ['Priestess', 'Sun'],
             ['Empress', 'Strength'],
             ['Emperor', 'Justice'],
             ['Hierophant', 'Death'],
             ['Lovers', 'Hermit'],
             ['Lovers', 'Star'],
             ['Chariot', 'Chariot'],
             ['Strength', 'Temperance'],
             ['Strength', 'Tower'],
             ['Death', 'Devil'],
             ['Devil', 'Moon']],
 'Death': [['Fool', 'Magician'],
           ['Fool', 'Strength'],
           ['Magician', 'Hierophant'],
           ['Priestess', 'Justice'],
           ['Priestess', 'Hanged Man'],
           ['Hierophant', 'Temperance'],
           ['Lovers', 'Strength'],
           ['Strength', 'Devil'],
           ['Hanged Man', 'Temperance'],
           ['Death', 'Death'],
           ['Tower', 'Star'],
           ['Sun', 'Judgement']],
 'Devil': [['Magician', 'Lovers'],
           ['Priestess', 'Strength'],
           ['Priestess', 'Temperance'],
           ['Emperor', 'Hanged Man'],
           ['Emperor', 'Temperance'],
           ['Chariot', 'Hermit'],
           ['Chariot', 'Death'],
           ['Justice', 'Moon'],
           ['Hermit', 'Sun'],
           ['Fortune', 'Star'],
           ['Death', 'Star'],
           ['Devil', 'Devil']],
 'Emperor': [['Magician', 'Justice'],
             ['Priestess', 'Empress'],
             ['Empress', 'Tower'],
             ['Empress', 'Judgement'],
             ['Emperor', 'Emperor'],
             ['Justice', 'Fortune'],
             ['Justice', 'Temperance'],
             ['Hermit', 'Judgement'],
             ['Fortune', 'Hanged Man'],
             ['Tower', 'Sun']],
 'Empress': [['Fool', 'Tower'],
             ['Magician', 'Hanged Man'],
             ['Priestess', 'Emperor'],
             ['Empress', 'Empress'],
             ['Hierophant', 'Judgement'],
             ['Lovers', 'Tower'],
             ['Lovers', 'Sun'],
             ['Justice', 'Star'],
             ['Fortune', 'Temperance'],
             ['Moon', 'Sun']],
 'Fool': [['Fool', 'Fool'],
          ['Magician', 'Strength'],
          ['Empress', 'Hierophant'],
          ['Empress', 'Death'],
          ['Emperor', 'Lovers'],
          ['Hierophant', 'Strength'],
          ['Chariot', 'Hanged Man'],
          ['Justice', 'Death'],
          ['Justice', 'Devil'],
          ['Temperance', 'Devil'],
          ['Moon', 'Judgement']],
 'Fortune': [['Priestess', 'Lovers'],
             ['Empress', 'Moon'],
             ['Emperor', 'Hierophant'],
             ['Hierophant', 'Hermit'],
             ['Chariot', 'Tower'],
             ['Fortune', 'Fortune'],
             ['Hanged Man', 'Devil'],
             ['Temperance', 'Tower'],
             ['Temperance', 'Moon'],
             ['Star', 'Judgement']],
 'Hanged Man': [['Fool', 'Empress'],
                ['Magician', 'Emperor'],
                ['Priestess', 'Tower'],
                ['Hierophant', 'Justice'],
                ['Hierophant', 'Devil'],
                ['Lovers', 'Judgement'],
                ['Justice', 'Sun'],
                ['Fortune', 'Tower'],
                ['Hanged Man', 'Hanged Man'],
                ['Death', 'Temperance']],
 'Hermit': [['Fool', 'Hierophant'],
            ['Magician', 'Death'],
            ['Priestess', 'Star'],
            ['Empress', 'Fortune'],
            ['Emperor', 'Death'],
            ['Chariot', 'Strength'],
            ['Hermit', 'Hermit'],
            ['Hanged Man', 'Tower'],
            ['Temperance', 'Judgement'],
            ['Devil', 'Sun'],
            ['Tower', 'Moon']],
 'Hierophant': [['Fool', 'Temperance'],
                ['Magician', 'Devil'],
                ['Magician', 'Sun'],
                ['Priestess', 'Chariot'],
                ['Priestess', 'Moon'],
                ['Emperor', 'Hermit'],
                ['Hierophant', 'Hierophant'],
                ['Justice', 'Strength'],
                ['Hermit', 'Strength'],
                ['Fortune', 'Devil'],
                ['Strength', 'Death'],
                ['Hanged Man', 'Sun'],
                ['Death', 'Moon']],
 'Judgement': [['Empress', 'Lovers'],
               ['Emperor', 'Sun'],
               ['Hierophant', 'Tower'],
               ['Lovers', 'Justice'],
               ['Hermit', 'Tower'],
               ['Star', 'Sun'],
               ['Judgement', 'Judgement']],
 'Justice': [['Fool', 'Moon'],
             ['Fool', 'Sun'],
             ['Magician', 'Empress'],
             ['Magician', 'Fortune'],
             ['Priestess', 'Judgement'],
             ['Empress', 'Emperor'],
             ['Emperor', 'Devil'],
             ['Hierophant', 'Fortune'],
             ['Justice', 'Justice'],
             ['Hanged Man', 'Star']],
 'Lovers': [['Fool', 'Fortune'],
            ['Magician', 'Hermit'],
            ['Magician', 'Moon'],
            ['Empress', 'Justice'],
            ['Empress', 'Star'],
            ['Emperor', 'Star'],
            ['Hierophant', 'Sun'],
            ['Lovers', 'Lovers'],
            ['Chariot', 'Moon'],
            ['Justice', 'Hanged Man'],
            ['Devil', 'Judgement']],
 'Magician': [['Fool', 'Star'],
              ['Magician', 'Magician'],
              ['Priestess', 'Hierophant'],
              ['Priestess', 'Fortune'],
              ['Priestess', 'Death'],
              ['Lovers', 'Moon'],
              ['Justice', 'Hermit'],
              ['Strength', 'Moon'],
              ['Temperance', 'Sun'],
              ['Devil', 'Tower']],
 'Moon': [['Fool', 'Priestess'],
          ['Fool', 'Chariot'],
          ['Priestess', 'Devil'],
          ['Lovers', 'Devil'],
          ['Chariot', 'Justice'],
          ['Chariot', 'Star'],
          ['Strength', 'Star'],
          ['Strength', 'Sun'],
          ['Hanged Man', 'Death'],
          ['Tower', 'Judgement'],
          ['Moon', 'Moon']],
 'Priestess': [['Fool', 'Hermit'],
               ['Magician', 'Chariot'],
               ['Magician', 'Star'],
               ['Priestess', 'Priestess'],
               ['Empress', 'Hanged Man'],
               ['Empress', 'Temperance'],
               ['Emperor', 'Judgement'],
               ['Hierophant', 'Moon'],
               ['Chariot', 'Fortune'],
               ['Chariot', 'Sun'],
               ['Hermit', 'Devil'],
               ['Hermit', 'Moon'],
               ['Death', 'Sun']],
 'Star': [['Fool', 'Justice'],
          ['Empress', 'Chariot'],
          ['Emperor', 'Tower'],
          ['Hierophant', 'Chariot'],
          ['Hermit', 'Fortune'],
          ['Hermit', 'Hanged Man'],
          ['Fortune', 'Death'],
          ['Fortune', 'Sun'],
          ['Hanged Man', 'Judgement'],
          ['Star', 'Star']],
 'Strength': [['Fool', 'Death'],
              ['Magician', 'Judgement'],
              ['Empress', 'Hermit'],
              ['Emperor', 'Chariot'],
              ['Hierophant', 'Lovers'],
              ['Lovers', 'Fortune'],
              ['Lovers', 'Temperance'],
              ['Chariot', 'Temperance'],
              ['Hermit', 'Death'],
              ['Hermit', 'Temperance'],
              ['Hermit', 'Star'],
              ['Strength', 'Strength'],
              ['Hanged Man', 'Moon'],
              ['Devil', 'Star']],
 'Sun': [['Fool', 'Judgement'],
         ['Empress', 'Devil'],
         ['Emperor', 'Fortune'],
         ['Hierophant', 'Hanged Man'],
         ['Lovers', 'Hanged Man'],
         ['Justice', 'Tower'],
         ['Fortune', 'Moon'],
         ['Death', 'Tower'],
         ['Temperance', 'Star'],
         ['Sun', 'Sun']],
 'Temperance': [['Fool', 'Emperor'],
                ['Fool', 'Devil'],
                ['Magician', 'Priestess'],
                ['Magician', 'Tower'],
                ['Priestess', 'Hermit'],
                ['Lovers', 'Chariot'],
                ['Lovers', 'Death'],
                ['Chariot', 'Devil'],
                ['Fortune', 'Strength'],
                ['Strength', 'Hanged Man'],
                ['Temperance', 'Temperance'],
                ['Star', 'Moon']],
 'Tower': [['Fool', 'Hanged Man'],
           ['Empress', 'Sun'],
           ['Emperor', 'Strength'],
           ['Emperor', 'Moon'],
           ['Hierophant', 'Star'],
           ['Fortune', 'Judgement'],
           ['Tower', 'Tower']]}
